# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        ember-version:
          - release
          - beta
          - canary
          - lts-3.4
          - lts-3.8
          - lts-3.12
          - lts-3.16
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (yarn)
        run: yarn install
      - name: Setup ember-try scenario
        run: yarn ember try:one ember-${{ matrix.ember-version }} --skip-cleanup --- cat package.json
      - name: Lint (js)
        run: yarn lint:js
      - run: yarn test
        env:
          CI: true
